# Backend Configuration for staging Environment
# Auto-generated by bootstrap/configure-backends.ps1
# Source: bootstrap/outputs.tf
#
# Values populated from Terraform outputs:
# - s3_bucket_name: terraform-state-donation-app-theophilus
# - dynamodb_table_name: terraform-state-lock
# - region: us-east-1

terraform {
  required_version = ">= 1.6.0"
  backend "s3" {
    bucket         = "terraform-state-donation-app-theophilus"
    key            = "environments/staging/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
  }
}
