#!/usr/bin/env pwsh
# Auto-configure backend.tf files with values from bootstrap outputs
# This script reads the Terraform outputs and updates all backend configurations

Write-Host "==================================================================" -ForegroundColor Cyan
Write-Host "     Auto-Configure Backend from Bootstrap Outputs                " -ForegroundColor Cyan
Write-Host "==================================================================" -ForegroundColor Cyan
Write-Host ""

# Check if we're in the bootstrap directory
if (-not (Test-Path "main.tf") -or -not (Test-Path "outputs.tf")) {
    Write-Host " Error: This script must be run from the bootstrap directory" -ForegroundColor Red
    Write-Host "   Current directory: $(Get-Location)" -ForegroundColor Yellow
    Write-Host "   Expected: .../3tier-aws-infrastructure/bootstrap" -ForegroundColor Yellow
    exit 1
}

# Check if Terraform is initialized
if (-not (Test-Path ".terraform")) {
    Write-Host "  Terraform not initialized. Running terraform init..." -ForegroundColor Yellow
    terraform init
    if ($LASTEXITCODE -ne 0) {
        Write-Host " Failed to initialize Terraform" -ForegroundColor Red
        exit 1
    }
}

Write-Host " Reading Terraform outputs from bootstrap..." -ForegroundColor Yellow
Write-Host ""

# Get Terraform outputs in JSON format
$outputJson = terraform output -json 2>&1

if ($LASTEXITCODE -ne 0) {
    Write-Host " Failed to read Terraform outputs" -ForegroundColor Red
    Write-Host "   Make sure you've run 'terraform apply' first" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "   Run these commands:" -ForegroundColor Cyan
    Write-Host "   terraform init" -ForegroundColor White
    Write-Host "   terraform apply" -ForegroundColor White
    exit 1
}

# Parse JSON
$outputs = $outputJson | ConvertFrom-Json

# Extract values from outputs.tf
$bucketName = $outputs.s3_bucket_name.value
$dynamoTable = $outputs.dynamodb_table_name.value
$region = $outputs.region.value

Write-Host " Retrieved configuration from outputs.tf:" -ForegroundColor Green
Write-Host "   S3 Bucket:       $bucketName" -ForegroundColor White
Write-Host "   DynamoDB Table:  $dynamoTable" -ForegroundColor White
Write-Host "   Region:          $region" -ForegroundColor White
Write-Host ""

# Function to create backend configuration
function New-BackendConfig {
    param(
        [string]$Environment,
        [string]$Bucket,
        [string]$DynamoTable,
        [string]$Region
    )
    
    $stateKey = "environments/$Environment/terraform.tfstate"
    
    return @"
# Backend Configuration for $Environment Environment
# Auto-generated by bootstrap/configure-backends.ps1
# Source: bootstrap/outputs.tf
#
# Values populated from Terraform outputs:
# - s3_bucket_name: $Bucket
# - dynamodb_table_name: $DynamoTable
# - region: $Region

terraform {
  backend "s3" {
    bucket         = "$Bucket"
    key            = "$stateKey"
    region         = "$Region"
    dynamodb_table = "$DynamoTable"
    encrypt        = true
  }
}
"@
}

# Configure each environment
$environments = @("dev", "staging", "prod")
$projectRoot = Split-Path -Parent (Get-Location)

Write-Host " Generating backend.tf files..." -ForegroundColor Yellow
Write-Host ""

foreach ($env in $environments) {
    $backendFile = Join-Path $projectRoot "environments\$env\backend.tf"
    
    Write-Host "   → $env environment..." -ForegroundColor Cyan
    
    # Check if directory exists
    $envDir = Join-Path $projectRoot "environments\$env"
    if (-not (Test-Path $envDir)) {
        Write-Host "      Creating directory: $envDir" -ForegroundColor Yellow
        New-Item -ItemType Directory -Path $envDir -Force | Out-Null
    }
    
    # Generate backend configuration
    $backendConfig = New-BackendConfig -Environment $env -Bucket $bucketName -DynamoTable $dynamoTable -Region $region
    
    # Write to file
    Set-Content -Path $backendFile -Value $backendConfig -Encoding UTF8
    
    Write-Host "       Created: environments\$env\backend.tf" -ForegroundColor Green
}

# Also update the main backend.tf if it exists
Write-Host ""
Write-Host "   → main backend.tf..." -ForegroundColor Cyan

$mainBackendFile = Join-Path $projectRoot "backend.tf"
$mainBackendConfig = @"
# Backend Configuration for Terraform State
# Auto-generated by bootstrap/configure-backends.ps1
# Source: bootstrap/outputs.tf
#
# Values populated from Terraform outputs:
# - s3_bucket_name: $bucketName
# - dynamodb_table_name: $dynamoTable
# - region: $region
#
# For environment-specific backends, see:
# - environments/dev/backend.tf
# - environments/staging/backend.tf
# - environments/prod/backend.tf

terraform {
  backend "s3" {
    bucket         = "$bucketName"
    key            = "terraform.tfstate"
    region         = "$region"
    dynamodb_table = "$dynamoTable"
    encrypt        = true
  }
}
"@

Set-Content -Path $mainBackendFile -Value $mainBackendConfig -Encoding UTF8
Write-Host "      Updated: backend.tf" -ForegroundColor Green

Write-Host ""
Write-Host "==================================================================" -ForegroundColor Green
Write-Host "                  Configuration Complete!                         " -ForegroundColor Green
Write-Host "==================================================================" -ForegroundColor Green
Write-Host ""
Write-Host " Summary:" -ForegroundColor Yellow
Write-Host "   • All backend.tf files updated with values from bootstrap/outputs.tf" -ForegroundColor White
Write-Host "   • S3 Bucket: $bucketName" -ForegroundColor White
Write-Host "   • DynamoDB Table: $dynamoTable" -ForegroundColor White
Write-Host "   • Region: $region" -ForegroundColor White
Write-Host ""
Write-Host " Next Steps:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. Navigate to your environment:" -ForegroundColor White
Write-Host "   cd ..\environments\dev" -ForegroundColor Cyan
Write-Host ""
Write-Host "2. Initialize Terraform:" -ForegroundColor White
Write-Host "   terraform init" -ForegroundColor Cyan
Write-Host ""
Write-Host "3. When prompted to migrate state, type: yes" -ForegroundColor White
Write-Host ""
Write-Host "Your remote state is now configured! " -ForegroundColor Green
Write-Host ""
