# Backend Configuration for Terraform State
# Auto-generated by bootstrap/configure-backends.ps1
# Source: bootstrap/outputs.tf
#
# Values populated from Terraform outputs:
# - s3_bucket_name: terraform-state-donation-app-theophilus
# - dynamodb_table_name: terraform-state-lock
# - region: us-east-1
#
# For environment-specific backends, see:
# - environments/dev/backend.tf
# - environments/staging/backend.tf
# - environments/prod/backend.tf

terraform {
  backend "s3" {
    bucket         = "terraform-state-donation-app-theophilus"
    key            = "terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
  }
}
